apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ template "locust.fullname" . }}-route
  annotations:
    haproxy.router.openshift.io/rewrite-target: /
    {{- if .Values.route.timeout.enabled }}
    haproxy.router.openshift.io/timeout: {{ .Values.route.timeout.duration }}
    {{- end }}
spec:
  path: {{ .Values.route.path | default "/" }}
  port:
    targetPort: external
  to:
    kind: Service
    name: {{ template "locust.fullname" . }}
  {{- if .Values.route.https }}
  tls:
    termination: edge
  {{- end }}