{{- if .Values.loadtest.environment_secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.loadtest.secret_name_api_key_locust }}
  labels:
{{ include "locust.labels" . | indent 4 }}
type: Opaque
stringData:
  x-api-key: {{ .Values.loadtest.environment_secret }}
{{- end }}
